### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by brandonzylstra** [PraxisLabs/vagrant-yaml#1]
`vagrant gem install vagrant-yaml` returns the Vagrant help.  There is no `vagrant gem` subcommand listed.

Vagrant version 1.4.2.

**Comment by ergonlogic** [comment]
Try `vagrant plugin install vagrant-yaml`. Note that I haven't tested vagrant-yaml against Vagrant 1.4.2, so ymmv.

**Comment by ergonlogic** [comment]
I updated to the new plugin architecture, so version 0.1.0+ should be compatible with Vagrant 1.1+. I've only tested against Vagrant 1.5.1, so far though.
